server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lfg777/lfg777.git
          search-paths: myconfig
      profile: myconfig_dev
  application:
    name: config-server
myName: adb