server:
  port: 8888
  application:
    name: config-server
myName: adb
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lfg777/lfg777
          search-paths: myconfig